# Copyright (C) 2022 Intel Corporation
# Licensed subject to the terms of the separately executed evaluation license agreement between Intel Corporation and you.

aggregator :
  defaults : plan/defaults/aggregator.yaml
  template : openfl.component.Aggregator
  settings :
    init_state_path : save/fets_seg_test_init.pbuf
    best_state_path : save/fets_seg_test_best.pbuf
    last_state_path : save/fets_seg_test_last.pbuf
    rounds_to_train : 3
    write_logs : true


collaborator :
  defaults : plan/defaults/collaborator.yaml
  template : openfl.component.Collaborator
  settings :
    delta_updates    : false
    opt_treatment    : RESET

data_loader :
  defaults : plan/defaults/data_loader.yaml
  template : openfl.federated.data.loader_gandlf.GaNDLFDataLoaderWrapper
  settings :
    feature_shape : [32, 32, 32]
  data_path : /home/ad_kagrawa2/.local/workspace

task_runner :
  template : src.fets_challenge_model.FeTSChallengeModel
  settings :
    train_csv           : seg_test_train.csv
    val_csv             : seg_test_val.csv
    device              : cpu
    gandlf_config  :
      batch_size: 1
      clip_grad: null
      clip_mode: null
      data_augmentation: {}
      data_postprocessing: {}
      data_preprocessing:
        normalize: null
      enable_padding: false
      in_memory: false
      inference_mechanism  :
        grid_aggregator_overlap: crop
        patch_overlap: 0
      learning_rate: 0.001
      loss_function: dc
      medcam_enabled: false
      output_dir: '.'
      metrics:
      - dice
      - dice_per_label
      - hd95_per_label
      model:
        amp: true
        architecture: resunet        
        base_filters: 32
        class_list:
        - 0
        - 1
        - 2
        - 4
        dimension: 3
        final_layer: softmax
        ignore_label_validation: null
        norm_type: instance
      nested_training:
        testing: 1
        validation: -5
      num_epochs: 1
      optimizer: 
        type: sgd
      parallel_compute_command: ''
      patch_sampler: label
      patch_size:
      - 64
      - 64
      - 64
      patience: 100
      pin_memory_dataloader: false
      print_rgb_label_warning: true
      q_max_length: 100
      q_num_workers: 0
      q_samples_per_volume: 40
      q_verbose: false
      save_output: false
      save_training: false
      scaling_factor: 1
      scheduler:
        type: triangle_modified
      track_memory_usage: false
      verbose: false
      version:
        maximum: 0.1.0
        minimum: 0.0.14
      weighted_loss: true
      modality: rad


network :
  defaults : plan/defaults/network.yaml

assigner:
  template : src.challenge_assigner.FeTSChallengeAssigner
  settings :
    training_tasks  :
      - aggregated_model_validation
      - train
      - locally_tuned_model_validation
    validation_tasks  :
      - aggregated_model_validation 

tasks :
  aggregated_model_validation:
    function : validate
    kwargs   :
      apply   : global
      metrics :
        - valid_loss
        - valid_dice
    
  locally_tuned_model_validation:
    function  : validate
    kwargs    :
      apply: local
      metrics :
        - valid_loss
        - valid_dice
    
  train:
    function : train
    kwargs   :
      metrics     :
      - loss
      - train_dice
      epochs : 1


compression_pipeline :
  defaults : plan/defaults/compression_pipeline.yaml
