# Copyright (C) 2022 Intel Corporation
# Licensed subject to the terms of the separately executed evaluation license agreement between Intel Corporation and you.

aggregator :
  defaults : plan/defaults/aggregator.yaml
  template : openfl.component.Aggregator
  settings :
    init_state_path : save/fets_seg_test_init.pbuf
    best_state_path : save/fets_seg_test_best.pbuf
    last_state_path : save/fets_seg_test_last.pbuf
    rounds_to_train : 3
    write_logs : true


collaborator :
  defaults : plan/defaults/collaborator.yaml
  template : openfl.component.Collaborator
  settings :
    delta_updates    : false
    opt_treatment    : RESET

data_loader :
  defaults : plan/defaults/data_loader.yaml
  template : openfl.federated.data.loader_gandlf.GaNDLFDataLoaderWrapper
  settings :
    feature_shape : [128,128,64] #[32,32,32]

task_runner :
  template : src.fets_challenge_model.FeTSChallengeModel
  settings :
    train_csv           : cla_test_train.csv
    val_csv             : cla_test_val.csv
    device              : cpu
    gandlf_config  :
      # label: None
      # clip_mode: norm
      # clip_grad: 0.1
      output_dir: '.'

      batch_size: 8
      data_augmentation: {}
      data_preprocessing: {}
      in_memory: false
      learning_rate: 0.001
      loss_function: ce
      metrics:
        - classification_accuracy       
      modality: rad
      model:
        amp: false
        onnx_export: false
        architecture: vgg11
        base_filters: 16
        class_list:
        - '0'
        - '1'
        - '2'
        - '3'
        dimension: 3
        final_layer: softmax
        num_channels: 4
        norm_type: instance
      weighted_loss: false
      num_epochs: 500
      nested_training:
        testing: 1
        validation: -4 ## these are 4 because there is one site (i.e., Site3) that has only 4 samples.
      optimizer: adam
      patch_sampler: uniform
      patch_size:
      - 128
      - 128
      - 64
      patience: 100
      q_max_length: 100
      q_num_workers: 0
      q_samples_per_volume: 40
      q_verbose: false
      save_masks: false
      scheduler: triangle
      version:
        maximum: 0.1.0
        minimum: 0.0.14


network :
  defaults : plan/defaults/network.yaml

assigner:
  template : src.challenge_assigner.FeTSChallengeAssigner
  settings :
    training_tasks  :
      - aggregated_model_validation
      - train
      - locally_tuned_model_validation
    validation_tasks  :
      - aggregated_model_validation 

tasks :
  aggregated_model_validation:
    function : validate
    kwargs   :
      apply   : global
      metrics :
        - valid_loss
        - valid_dice
    
  locally_tuned_model_validation:
    function  : validate
    kwargs    :
      apply: local
      metrics :
        - valid_loss
        - valid_dice
    
  train:
    function : train
    kwargs   :
      metrics     :
      - loss
      - train_dice
      epochs : 1


compression_pipeline :
  defaults : plan/defaults/compression_pipeline.yaml
